# Generated by Django 5.2.11 on 2026-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(default='@support', max_length=100)),
                ('email', models.EmailField(default='support@pos.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Help Info',
                'verbose_name_plural': 'Help Info',
            },
        ),
        migrations.CreateModel(
            name='PrinterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(default='Default Printer', max_length=200)),
                ('printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('paper_size', models.CharField(choices=[('58mm', '58mm'), ('80mm', '80mm')], default='58mm', max_length=10)),
                ('auto_print', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Printer Settings',
                'verbose_name_plural': 'Printer Settings',
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
