# Generated by Django 5.2.11 on 2026-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_image_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_add_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_make_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_use_pos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_users',
            field=models.BooleanField(default=False),
        ),
    ]
