# Generated by Django 5.2.11 on 2026-03-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type', models.CharField(choices=[('add', 'Add'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock history entry',
                'verbose_name_plural': 'Stock history',
                'ordering': ['-created_at'],
            },
        ),
    ]
