# Generated by Django 5.2.11 on 2026-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pcs'), ('kg', 'Kg')], default='pcs', max_length=10),
        ),
    ]
