# Generated by Django 5.2.11 on 2026-03-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_unit_product_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('piece', 'Piece'), ('weight', 'Weight')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
