# Generated by Django 5.2.11 on 2026-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_unit_type_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=10),
        ),
    ]
